// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'AIzaSyD_xevTRgvKZifenPUEsav_XMwgkl61BwM',
    authDomain: 'riqma-pro.firebaseapp.com',
    projectId: 'riqma-pro',
    storageBucket: 'riqma-pro.firebasestorage.app',
    messagingSenderId: '209996546252',
    appId: '1:209996546252:web:dbfbc5c615f0bd89bf8269',
  );
}
